from __future__ import annotations

from tesis_unicamp.finetuning.embeddings.config import (
    DEFAULT_BASE_MODEL,
    DEFAULT_HUB_ORG,
    EMBEDDING_FINETUNING_DATASET_IDS,
    LORA_ALPHA,
    LORA_DROPOUT,
    LORA_R,
)

MAX_SEQ_LENGTH = 3072
MAX_QUERY_TOKENS = 512
MAX_DOC_TOKENS = 512
MAX_POSITIVE_TOKENS = 512
MAX_CONTEXT_DOCS = 5

TRAIN_BATCH_SIZE = 128
MINI_BATCH_SIZE = 32

RELEVANT_DOC_RATIO = 0.7
DEFAULT_DATASET_SEED = 42

DEFAULT_WANDB_PROJECT = "qwen3-embedding-context-finetuning"

__all__ = [
    "DEFAULT_BASE_MODEL",
    "DEFAULT_DATASET_SEED",
    "DEFAULT_HUB_ORG",
    "DEFAULT_WANDB_PROJECT",
    "EMBEDDING_FINETUNING_DATASET_IDS",
    "LORA_ALPHA",
    "LORA_DROPOUT",
    "LORA_R",
    "MAX_CONTEXT_DOCS",
    "MAX_DOC_TOKENS",
    "MAX_POSITIVE_TOKENS",
    "MAX_QUERY_TOKENS",
    "MAX_SEQ_LENGTH",
    "MINI_BATCH_SIZE",
    "RELEVANT_DOC_RATIO",
    "TRAIN_BATCH_SIZE",
]
